---
title: "Poster"
author: 
  - Merly Klaas
  - Havisha Khurana
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.height = 6,
                      fig.width = 8)
pacman::p_load("tidyverse","rio","here","janitor", "usmap", "ggthemes", "ggrepel","edld652", "patchwork", "gghighlight", "ggtext", "viridis")

```

```{r}
#theme for all visuals

plot_theme <- function() {
  theme(
  text = element_text(family = 'sans', size = 9),
  plot.title.position = "plot",
  plot.title = element_text(face="bold", size = 18),
  plot.subtitle = element_text(size = 14),
  plot.caption = element_text(size = 12,
                              color ="gray30",
                              hjust = 1),
  axis.title = element_text(face="bold", size = 9),
  axis.text = element_text(face="bold", size = 9),
 # axis.text.y = element_text(margin=margin(r=1))
  )
}

ggpreview <- function(...) {
  fname <- tempfile(fileext = ".png")
  ggsave(filename = fname, ...)
  system2("open", fname)
  invisible(NULL)
}

```


```{r loading-data}
us <- sf::read_sf(here("data","us_states.shp"))
state_r2b <- import(here("Data", "state_r2b.csv"))
dist_r2b <- import(here("Data", "dist_r2b.csv"))
state <- import(here("data", "state.csv"))
```



```{r include=FALSE}
#### Diverging Plots Math
math <- state %>%
  drop_na(allmath, st)

math$math_z <- round(math$allmath - mean(math$allmath),2)
math$math_type <-ifelse(math$math_z < 0, "elow", "above")


```


```{r}
#Diverging plot with geom_bar
ppmath <- math %>%
  mutate(st = fct_reorder(st, math_z)) %>%
  ggplot(aes(math_z, st)) +
  geom_bar(stat = "identity", aes(fill =math_type), width=0.5)+
  scale_fill_manual(name = "Average Math",
                    values = c("above" = "#015193", "below"="#e3007d")) +
  scale_x_continuous(breaks = c(-26.76 , 0 , 23.24),
                       labels = c(30, 56.76, 80),
                     expand = c(0,0)) +
  labs(title= "High school students proficienct in Math Test (2018-2019)",
       subtitle = "Percentage profieciency varied widely, between 28% to 90%.",
       captions = "Note: States missing from the graph did not report their data",
        x = "",
       y = "") +
   theme_minimal() +
  plot_theme()+
   theme(legend.position="none", 
         panel.grid = element_blank())
        #  plot.title.position = "plot",
        #  plot.title = element_text(face="bold"),
        # plot.subtitle = element_text(face="italic"),
        # plot.caption = element_text(color ="gray30",hjust = 1))
ppmath
```


```{r}
rla <- state %>%
  drop_na(allrla, st)

rla$rla_z <- round(rla$allrla - mean(rla$allrla),2)
rla$rla_type <-ifelse(rla$rla_z < 0, "below", "above")


prla <- rla %>%
  mutate(st= fct_reorder(st,rla_z)) %>%
  ggplot(aes(rla_z, st)) +
  geom_bar(stat = "identity", aes(fill =rla_type), width=0.5)+
  scale_fill_manual(name = "Average Math",
                    values = c("above" = "#015193", "below"="#e3007d")) +
  scale_x_continuous(breaks = c(-30,0,20),
                       labels = c(37.97, 67.97, 87.97),
                     expand = c(0,0)) +
  labs(title= "High school students proficienct in Reading Test (2018-2019)",
       subtitle = "Percentage proficient varied widely, between 29% to 94%",
       captions = "Note: States missing from the graph did not report their data",
        x = "",
       y = "") +
    theme_minimal() +
    plot_theme()+
   theme(legend.position="none", 
         panel.grid = element_blank())

        
prla
```

```{r}
textbook_us <- left_join( us, state_r2b, by = c("name" = "stnam")) %>%
  mutate(Textbook = round(stperstudbook,2)) %>%
mutate(bins = cut(Textbook, breaks = c(0,20,40,60,80,100, 120))) %>% 
        ggplot(aes(geometry = geometry, fill = bins)) +
    	geom_sf(color = "white", size = 0.2)+
 scale_fill_manual(values = c("#F2E289", "#E8FACF","#BCDFB0","#8EC495", "#00777E","#005C88"),
                             name = "($)") +
  theme_minimal() +
  labs(fill = "Textbook Spending \nper Student",
       title = "State Textbook Spending Per Student",
       subtitle = "Textbook Spending per student varied between $14 - $107 across the states")+
     #  caption = "Source: U.S. Department of Education, National Center for Education Statistics, Common Core of Data (CCD)") +
    plot_theme()+
    theme(
         panel.grid = element_blank(),
        #  plot.title.position = "plot",
        #  plot.title = element_text(face="bold"),
        # plot.subtitle = element_text(face="italic"),
        # plot.caption = element_text(color ="gray30",hjust = 1),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        axis.text.y = element_blank(),
        legend.key.height = unit(0.1,"cm"),
        legend.text = element_text(size = 9),
        legend.title = element_text(size = 9),
        rect = element_blank(),
        panel.grid.major = element_blank())


textbook_us
```

```{r}
ols <- state_r2b%>%
  select(stnam, stperstudbook, allmath) %>%
  drop_na() %>%
  filter(!stnam == "District Of Columbia") %>%
  ggplot(aes(stperstudbook, allmath))+
  geom_point( color = "gray", size = 4, alpha = 0.4) +
  geom_smooth(fill= "gray90",method = "lm", color = "gray")+
  geom_point(data=filter(state_r2b,
                         stnam == "Virginia" |
                           stnam== "Nebraska"|
                           stnam== "New York"),
             color = "#015193",
             alpha = 0.8,
             size =4)+
geom_point(data=filter(state_r2b,
                       stnam == "Tennessee"|
                         stnam== "Rhode Island"|
                         stnam== "Minnesota"),
           color = "#E3007D",
           alpha = 0.8,
           size =4) +
  geom_text_repel(data= subset(state_r2b,
                               stnam == "Virginia" |
                                 stnam== "Nebraska"|
                                 stnam =="New York" |
                                 stnam == "Tennessee" |
                                 stnam== "Rhode Island"|
                                 stnam== "Minnesota"),
                               aes(label =stnam)) +
  theme_minimal()+
  xlim (14,108) +
    labs(title= "The relationship between Textbook Spending & Math Achievement in High School",
         subtitle = "States that spent more on textbook tend to have higher percentage of proficient student in Math",
      x = "Textbook spending per student",
       y = "% of Students at & above Proficiency Level",
      size = "Spending \nper Student",
      caption = "3 Top/Bottom States with Percent of Student at and above Math Proficiency \nare labeled and colored blue/red, respectively")+
    geom_richtext(x=90,y=50, label="<i>r</i> = 0.33 \n<i>p</i> = 0.045", size = 2, color = "gray30")+
  theme(legend.position = "bottom",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  plot_theme()
        # plot.title = element_text(face="bold"),
        # plot.subtitle = element_text(face="italic"),)
ols
```

## Diversity plots

```{r}
sm <- get_data("NCES_CCD_nonfiscal_state_2017_2021_membership") %>% 
    clean_names()

#Grade only K-12
#Student count by race_ethnicity in K-12 


sm <- subset(sm, grepl(("^G|^K"), grade))

sm <- sm %>% 
    filter(grade != "Grade 13") %>%
    filter(!race_ethnicity %in% c("Not Specified", "No Category Codes")) %>% 
    group_by(st, race_ethnicity, school_year, year) %>% 
    summarise(
        student = sum(student_count, na.rm = TRUE) #students belonging to one race across grade
    )
```

```{r}
sm_wide <- sm %>% 
    filter(!(st %in% c("BI","AS","GU","PR","VI", "DA", "IL"))) %>% 
          #removing us territories and states that don't have data for all years
    group_by(year, race_ethnicity) %>% 
    summarise(
        us_total = sum(student) 
    ) %>% 
    ungroup() %>% 
    pivot_wider(
        names_from = year,
        names_prefix = "year_",
        values_from = us_total
    ) %>% 
    mutate(
        change_1718 = year_2018 - year_2017,
        change_1819 = year_2019 - year_2018,
        change_1920 = year_2020 - year_2019,
        change_2021 = year_2021 - year_2020,
        pchange_1718 = ifelse(year_2017 == 0, NA, (change_1718)/year_2017),
        pchange_1819 = ifelse(year_2018 == 0, NA, (change_1819)/year_2018),
        pchange_1920 = ifelse(year_2019 == 0, NA, (change_1920)/year_2019),
        pchange_2021 = ifelse(year_2020 == 0, NA, (year_2021 - year_2020)/year_2020)
    )
```

```{r}
smw_change <- sm_wide%>% 
  mutate(
    re = case_when(
       race_ethnicity == "Native Hawaiian or Other Pacific Islander" ~ "NHPI",
       race_ethnicity == "Black or African American" ~ "Black",
       race_ethnicity == "American Indian or Alaska Native" ~ "AIAN",
       race_ethnicity == "Two or more races" ~ "Multiracial",
       race_ethnicity == "Hispanic/Latino" ~ "Hispanic/Latino",
       race_ethnicity == "White" ~ "White",
       race_ethnicity == "Asian" ~ "Asian"
    )) %>% 
  select(re, starts_with("change_")) %>% 
    pivot_longer(
        cols = starts_with("change_"),
        names_to = "years",
        values_to = "raw",
        names_prefix = "change_"
    )


p1 <- ggplot(smw_change, aes(x = years, y = raw, group = re))+
    geom_point(aes(color = re), show.legend = FALSE)+
    geom_line(aes(color = re), show.legend = FALSE)+
    geom_text_repel(data=subset(smw_change,
                       years == 2021),
               aes(
                 label = re,
                 color = re
               ),
               show.legend = FALSE,
               nudge_x = 0.4,
               nudge_y = 10000
             ) +
    scale_y_continuous(
        labels = scales::comma
    )+
    scale_x_discrete(
           # expand = c(0,0),
        labels = c("Raw change from 2017-18","18-19", "19-20", "20-21")
    )+
    labs(
        x = "",
        y = "",
        subtitle = "Raw Change",)+
    #     caption = "NHPI = Native Native Hawaiian or Other Pacific Islander \nAIAN = American Indian or Alaska Native \nNote: Missing data from Illinois"
    # )+
    scale_color_manual(
        values = c("#E62790", "#00347B","#249EDC",
                   "#00906E","#6929C4","#20659D",
                   "#CF77AD")
    )+
  theme_minimal()+
    theme(
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())+
  plot_theme()
```


```{r}
smw_pchange <- sm_wide%>% 
  mutate(
    re = case_when(
       race_ethnicity == "Native Hawaiian or Other Pacific Islander" ~ "NHPI",
       race_ethnicity == "Black or African American" ~ "Black",
       race_ethnicity == "American Indian or Alaska Native" ~ "AIAN",
       race_ethnicity == "Two or more races" ~ "Multiracial",
       race_ethnicity == "Hispanic/Latino" ~ "Hispanic/Latino",
       race_ethnicity == "White" ~ "White",
       race_ethnicity == "Asian" ~ "Asian"
    )) %>% 
  select(re, starts_with("pchange_")) %>% 
    pivot_longer(
        cols = starts_with("pchange_"),
        names_to = "years",
        values_to = "raw",
        names_prefix = "pchange_"
    )


p2 <- ggplot(smw_pchange, aes(x = years, y = raw, group = re))+
    geom_point(aes(color = re), show.legend = FALSE)+
    geom_line(aes(color = re), show.legend = FALSE)+
    geom_text_repel(data=subset(smw_pchange,
                       years == 2021),
               aes(
                 label = re,
                 color = re
               ),
               show.legend = FALSE,
               nudge_x = 0.4
             ) +
    scale_y_continuous(
        labels = scales::comma
    )+
    scale_x_discrete(
           # expand = c(0,0),
        labels = c("%change from 2017-18","18-19", "19-20", "20-21")
    )+
    labs(
        x = "",
        y = "",
        subtitle = "% Change") +
    #     caption = "NHPI = Native Native Hawaiian or Other Pacific Islander \nAIAN = American Indian or Alaska Native \nNote: Missing data from Illinois"
    # )+
    scale_color_manual(
        values = c("#E62790", "#00347B","#249EDC",
                   "#00906E","#6929C4","#20659D",
                   "#CF77AD")
    )+
  theme_minimal()+
    theme(
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())+
  plot_theme()
```

```{r}
p1 + p2 +
  plot_annotation(
  title = 'Changes in K-12 Student Composition',
  subtitle = 'COVID-19 pandemic impacted student enrollment for all races and ethnicities',
  caption = 'NHPI = Native Native Hawaiian or Other Pacific Islander \nAIAN = American Indian or Alaska Native \nNote: Missing data from Illinois'
  ) &
  plot_theme()

#ggpreview(width = 15, height = 7, unit = "in")
#ggsave(here::here("plot","change.png"), width = 15, height = 7, unit = "in")
```

```{r}
sm_18 <- sm %>%
    filter(year == "2018") %>% 
    group_by(st, race_ethnicity) %>% 
    summarise(
        stu_total = sum(student)
    ) %>% 
    group_by(st) %>% 
    mutate(
        total = sum(stu_total),
        percent_s = round((stu_total*100/total),3)
    ) %>% 
    left_join(us, by = "st") 

```

```{r}
stu_map1 <- sm_18 %>%  
        filter(!st %in% c("BI","AS","GU","PR","VI")) %>% 
        mutate(
        race_ethnicity = ifelse(race_ethnicity == "Native Hawaiian or Other Pacific Islander", "Native Hawaiian or \nOther Pacific Islander", race_ethnicity)
        ) %>% 
        mutate(bins = cut(percent_s, 
                          breaks = c(0,2,10,25,50,75, 91),
                          labels = c("<2%","2-10%","10-25%","25-50%","50-75%",">75%"))) %>% 
        ggplot(aes(geometry = geometry, fill = bins)) +
    	geom_sf(color = "gray30", size = 0.2) +
    	#guides(color = "none") +
        scale_fill_manual(values = c("#E8D7FA","#E2B5ED","#E390D6",
                                     "#E565B7","#E62790","#B4228E"),
                             name = "Percent of Students") +
        labs(
            title = "Student Diversity in K-12 Public Schools (2017-18)",
            subtitle = "52% of all students identify as non-White",
           # caption = " \n \nSource: U.S. Department of Education, National Center for Education Statistics, Common Core of Data (CCD)"
        )+
        guides(fill = guide_legend(nrow = 1))+
        facet_wrap(~ race_ethnicity, nrow = 2) +
  ggthemes::theme_map(base_size = 14) +
    theme(
        strip.background = element_blank(),
        legend.position = "top",
        legend.justification="right",
        legend.title = element_text(size = 9),
        legend.text  = element_text(size = 9),
        legend.key.size = unit(1, "lines"),
        text = element_text(family = 'sans', size = 12),
        plot.title.position = "plot",
        plot.title = element_text(face="bold", size = 18),
        plot.subtitle = element_text(size = 14),
        plot.caption = element_text(size = 12,
                                    color ="gray30",
                                    hjust = 1))
    
stu_map1

#ggpreview(width = 10, height = 6, unit = "in")
#ggsave(here::here("plot","map.png"), width = 10, height = 6, unit = "in")
```

```{r}
stu_map2 <- sm_18 %>%  
        filter(!st %in% c("BI","AS","GU","PR","VI")) %>% 
        mutate(
        race_ethnicity = ifelse(race_ethnicity == "Native Hawaiian or Other Pacific Islander", "Native Hawaiian or \nOther Pacific Islander", race_ethnicity)
        ) %>% 
        mutate(bins = cut(percent_s, 
                          breaks = c(0,2,10,25,50,75, 91),
                          labels = c("<2%","2-10%","10-25%","25-50%","50-75%",">75%"))) %>% 
        ggplot(aes(geometry = geometry, fill = bins)) +
    	geom_sf(color = "gray70", size = 0.2) +
    	#guides(color = "none") +
        scale_fill_viridis_d(option = "A",
                             direction = -1,
                             name = "Percent of Students") +
        labs(
            title = "Student Diversity in K-12 Public Schools (2017-18)",
            subtitle = "52% of all students identify as non-White",
           # caption = " \n \nSource: U.S. Department of Education, National Center for Education Statistics, Common Core of Data (CCD)"
        )+
        guides(fill = guide_legend(nrow = 1))+
        facet_wrap(~ race_ethnicity, nrow = 2) +
        ggthemes::theme_map(base_size=8) +
    theme(
        strip.background = element_blank(),
        legend.position = "top",
        legend.justification="right",
        legend.title = element_text(size = 6), 
        legend.text  = element_text(size = 6),
        legend.key.size = unit(1, "lines"),
        plot.title.position = "plot",
        text=element_text(family= "sans"),
        plot.title = element_text(face="bold"),
        plot.subtitle = element_text(face="italic"),
        #plot.caption = element_text(color ="gray30",hjust = 0),
        axis.title = element_text(face = "bold")
    )

stu_map2
```
```{r}
#Note to self: Missing total student data for AS(2017), DA(2017), and IL (2021)


#Percent of student in a certain race/ethnicity for each year

sm_p <- sm %>% 
    group_by(st, year) %>% 
    mutate(
        total = sum(student),
        percent_s = round((student*100/total),3)
    )  
```



```{r}
teacher <- rio::import(here("data","ntps1718_fltable01_t1s.xlsx"), skip = 2, n_max = 62) %>% 
    clean_names() %>% 
    select(-c(3,5,7,9,11,13,15)) %>% 
    filter(!is.na(state))
teacher[teacher == "#"] <- 0 #code-book says # means rounds to 0
teacher[teacher == "‡"] <- NA #code-book says this symbol means there were inconsistencies in the data

teacher <- teacher %>% 
    select(
        "White" = white_non_hispanic,
        "Black or African American" = black_or_african_american_non_hispanic,
        "American Indian or Alaska Native" = american_indian_alaska_native_non_hispanic,
        "Asian" = asian_non_hispanic,
        "Hispanic/Latino" = hispanic_regardless_of_race1,
        "Native Hawaiian or Other Pacific Islander" = native_hawaiian_pacific_islander_non_hispanic,
        "Two or more races" = two_or_more_races_non_hispanic,
        everything()
    ) 

stu_teacher <- teacher %>% 
    pivot_longer(
        cols = c(1:7),
        names_to = "race",
        values_to = "percent_t"
    ) %>%  
    mutate(percent_t = readr::parse_number(percent_t)) %>%  
    filter(state!= "United States") %>% 
    left_join(us %>% select(name, st), by = c("state" = "name")) %>% 
    left_join(sm_p %>% 
                  filter(year == 2018) %>% 
                  select(st, race_ethnicity, percent_s), 
              by = c("st", "race" = "race_ethnicity")) %>% 
    pivot_longer(
        cols = c("percent_t", "percent_s"),
        names_to = "profession",
        names_prefix = "percent_",
        values_to = "percent"
    )
```

```{r}
st_binary <- stu_teacher %>% 
    mutate(
        rbinary = ifelse(race == "White", "White","People of Color")
    ) %>%
    # filter(state == "Hawaii") %>% 
    # group_by(profession) %>% 
    # summarise(
    #     percent_total = sum(percent, na.rm = TRUE)
    # )
    group_by(state, rbinary, profession) %>% 
    summarise(
        percent_total = sum(percent, na.rm = TRUE)
    ) %>% 
    filter(rbinary != "White" & state != "United States") %>%
    mutate(
        profession = ifelse(profession == "s", "Student", "Teacher")
    ) %>% 
    right_join(us, by = c("state" = "name")) %>% 
    filter(!state %in% c("Maryland", "District of Columbia")) 
```

```{r}
dotplot <- ggplot(st_binary, aes(x = percent_total, y = forcats::fct_reorder(st, percent_total))) +
    geom_line(aes(group = st), 
            linetype = "dotted", color = "gray80")+
    geom_point(aes(color = profession), size = 1.5)+
    geom_text(aes(x=percent_total,
                  y=st,
                  label = round(percent_total,0),
                  color = profession),
               nudge_x = 2, size = 3, family = "sans",
              show.legend = FALSE)+
    scale_color_manual(limits = c("Teacher", "Student"),
                      values = c("#00347B","#E62790"), 
                       name = "")+
    scale_x_continuous(expand = c(0,0), limits = c(0,95))+
   theme_minimal()+
    labs(
        x = "Percent",
        y  = "",
        title = "Student Teacher Diveristy Gap (SY 2017-18)",
        subtitle = "52% of all K-12 students identify as non-White but only \n21% of all teachers identify as non-White",
        caption = " \n \nNo teacher data for Maryland and Washington DC."
        )+
    plot_theme()+
    theme(
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text.x = element_blank(),
        axis.line.x = element_line(colour = "gray90"),
        legend.key = element_rect(fill = "white", colour = NA),
        legend.box.background = element_blank(),
        legend.position = "top",
        legend.justification = "right",
        legend.direction = "horizontal")


    #     plot.title.position = "plot",
    #     text=element_text(family= "sans"),
    #     plot.title = element_text(face="bold"),
    #     plot.subtitle = element_text(face="italic"),
    #     plot.caption = element_text(color ="gray30",hjust = 0),
    #     axis.title = element_text(face = "bold")
    # )

dotplot
```

```{r}
#ggpreview(height = 9, width = 8, unit = "in")
#ggsave(here("plot","dotplot.png"), height = 9, width = 8, unit = "in")
```

